INSERT INTO venues (venue_id, venue_name, venue_size, venue_location) VALUES
(1, 'NLT', 250, 'Opposite Natural Science Faculty'),
(2, 'MLT', 250, 'Opposite library'),
(3, 'Sapetro', 500, 'Beside Faculty of Engineering'),
(4, 'SEAP', 120, 'Beside Faculty of Engineering'),
(5, 'Auditorium A', 1000, 'Central Campus'),
(6, 'Auditorium B', 800, 'Near Administrative Block'),
(7, 'Lecture Hall 1', 200, 'Behind Faculty of Arts'),
(8, 'Lecture Hall 2', 200, 'Behind Faculty of Arts'),
(9, 'Seminar Room 1', 50, 'Inside Faculty of Science'),
(10, 'Seminar Room 2', 50, 'Inside Faculty of Science'),
(11, 'Computer Lab 1', 100, 'Inside ICT Building'),
(12, 'Computer Lab 2', 100, 'Inside ICT Building'),
(13, 'Engineering Hall', 400, 'Faculty of Engineering'),
(14, 'Medical Hall', 300, 'Faculty of Medicine'),
(15, 'Law Auditorium', 600, 'Faculty of Law'),
(16, 'Physics Lab', 150, 'Faculty of Science'),
(17, 'Chemistry Lab', 150, 'Faculty of Science'),
(18, 'Biology Lab', 150, 'Faculty of Science'),
(19, 'Library Conference Room', 80, 'Inside Library'),
(20, 'Multipurpose Hall', 1200, 'Main Campus');
